module.exports = {
  thomasFrankSidebar: [
    {
      type: 'category',
      label: 'Thomas Frank Book',
      items: [
        {
          type: 'autogenerated',
          dirName: 'thomas-frank',
        },
      ],
    },
  ],
  feelGoodSidebar: [
    {
      type: 'category',
      label: 'Feel-Good Productivity',
      items: [
        {
          type: 'autogenerated',
          dirName: 'feel-good',
        },
      ],
    },
  ],
  mattDavellaSidebar: [
    {
      type: 'category',
      label: "Matt D'Avella Subtitles Book",
      items: [
        {
          type: 'autogenerated',
          dirName: 'matt-davella',
        },
      ],
    },
  ],
};
